

services:
  postgres:
    image: postgres:latest
    container_name: financial_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: financial_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
